export const colors = {
  primary: "#1F5C3F",
  primaryDark: "#163C2E",
  primaryLight: "#8DC63F",
  background: "#F5F6F4",
  white: "#FFFFFF",
  text: "#1A1D1B",
  textMuted: "#6B716C",
  border: "#E4E6E2",
  danger: "#E11D48",
  success: "#16A34A",
  warning: "#F59E0B",
  bubbleMine: "#E8F5E0",
  bubbleOther: "#FFFFFF",
  lightGreenBg: "#E8F5E0",
  // Derived tokens added for the modernized UI pass (existing hues above are unchanged)
  shadow: "#0F2A1E",
  overlay: "rgba(11, 31, 22, 0.45)",
  accentSoft: "#DCEFC9",
  cardBorder: "#E4E6E2",
  // Status badge tokens (from the approved ui-preview redesign)
  statusPendingBg: "#FFF1DE",
  statusPendingText: "#B5590A",
  statusAcceptedBg: "#E7F0FA",
  statusAcceptedText: "#1D5FA8",
  statusDoneBg: "#E6F4EA",
  statusDoneText: "#1E7A3D",
  textSecondary: "#6B716C",
  textFaint: "#9CA39D",
};
